resources:
  db: h2
  logs: C:\temp\logs\
  secure: false
spring:
  datasource:
    url: jdbc:h2:mem:retailkart
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-only
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /db-console